Improve DCAT harvesting
AstunTechnology/iso19139.gemini23 pull request #152
Opened 2024-11-21 14:41 UTC by alexarobu

This improves the general XML formatting of the file and adds a link back to the Spatial Hub

2024-11-21 17:13 UTC, archaeogeek commented on src/main/plugin/iso19139.gemini23/convert/fromSPARQL-DCAT.xsl
> +                          <xsl:text>https://data.spatialhub.scot/dataset/</xsl:text>
Not sure we should be hard-coding this in the standard Gemini branch

2024-11-21 17:14 UTC, archaeogeek commented on src/main/plugin/iso19139.gemini23/convert/fromSPARQL-DCAT.xsl
> +                        <gco:CharacterString>A link to the CKAN metadata record on the Spatial Hub.</gco:CharacterString>
Same, this probably shouldn't be hard-coded in the standard Gemini file

2024-11-21 17:15 UTC, archaeogeek requested changes
From what I can tell, this is hard-coding the spatialhub address in the file (unless I mistook what's going on). I'd be reluctant for that to go into the standard plugin- so you might want to think about a way of doing this within the scotgov code instead- even if it's just to overwrite the standard one when you deploy

2024-11-22 13:10 UTC, alexarobu commented
@archaeogeek fair enough, I don't know why I didn't think it should have been more generic, how about now?

2024-11-26 08:58 UTC, archaeogeek approved these changes
Great! Happy to approve

2024-12-02 10:58 UTC, alexarobu commented
> Great! Happy to approve

Super, thanks @archaeogeek :pray:

2024-12-02 10:58 UTC, merged